AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  VideoToThumb:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: hello-world
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref VideoToThumbLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: hello-world
          Name: 0
          Environment:
            - Name: AWS_REGION
              Value: us-west-2
            - Name: INPUT_VIDEO_FILE_URL
              Value: https://s3.amazonaws.com/your-s3-bucket-name/test.mp4
            - Name: OUTPUT_S3_PATH
              Value: your-s3-bucket-name/your-thumbnail-folder-name
            - Name: OUTPUT_THUMBS_FILE_NAME
              Value: test.png
            - Name: POSITION_TIME_DURATION
              Value: 00:01
      Cpu: 1024
      ExecutionRoleArn: !GetAtt VideoToThumbExecutionRole.Arn
      Memory: 2048
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !GetAtt VideoToThumbTaskRole.Arn
      Volumes: []
    DependsOn: VideoToThumbLogGroup
    Metadata:
      StackeryName: stackery-video-to-thumb-task-def
  VideoToThumbExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-VideoToThumb-execution
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: DownloadDockerImagesFromECR
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:*:*:log-group:/stackery/task/${AWS::StackName}-*
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'
  VideoToThumbTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-VideoToThumb-task
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
  VideoToThumbLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /stackery/task/${AWS::StackName}-VideoToThumb/hello-world
  VideoFiles:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-videofiles
    Metadata:
      StackeryName: rg-stackery-video-files
  Thumbnails:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-thumbnails
    Metadata:
      StackeryName: rg-stackery-thumbnails
  onUploadVideoStackery:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-onUploadVideoStackery
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: triggerOnUploadVideoStackery
      CodeUri: src/onUploadVideoStackery
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Events:
        VideoFiles:
          Type: S3
          Properties:
            Bucket: !Ref VideoFiles
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*
    Metadata:
      StackeryName: triggerOnUploadVideoStackery
  onThumbnailCreationStackery:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-onThumbnailCreationStac
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: triggerOnThumbnailCreationStackery
      CodeUri: src/onThumbnailCreationStackery
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Events:
        Thumbnails:
          Type: S3
          Properties:
            Bucket: !Ref Thumbnails
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*
    Metadata:
      StackeryName: triggerOnThumbnailCreationStackery
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)